### Delete all data via API
DELETE http://localhost:5000/data


### Check ES
GET http://192.168.21.136:9200/dv/_search?pretty
Content-Type: application/json

{
  "query": {"match_all": {}}
}


### Get a document using full link
GET http://localhost:5000/data?id=https%3A%2F%2Fdoi.org%2F10.11588%2Fdata%2F10006

### short link
GET http://localhost:5000/data?id=10006

###